
    spring:
      application:
        name: Api-Gateway
      cloud:
        gateway:
          routes:
            - id: StudentService
              uri: lb://StudentService
              predicates:
                - Path=/api/**
            - id: LibraryService
              uri: lb://LibraryService
              predicates:
                - Path=/api/**
            - id : BookService
              uri : lb://BookService
              predicates:
                - Path=/api/**
                    
    server:
      port: 2000
        
    eureka:
      instance:
        hostname: localhost
           